# Generated by Django 5.1.6 on 2025-03-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_sitesetup_options_menulink_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.sitesetup'),
        ),
    ]
